travis:
  secure:
    BINSTAR_TOKEN: nZV5SweK+1Au7Aaz1n5dmo2gLUyz+Quucf3EUYpOxukMLpOVpHypqgK7TZr1NAys2ixVlDlQm2RVIaSLHyg744LX0958S2TBT2uchus5Kku3jQHqDIFAw8JyrPvJI7yxkC4+r2gx9G9xyXAq6M39rjQbAYp6QB01xXgT07UstywUMkyl2F/xFAkVEqZE+2n9IjWdAqF1l33hirQqvdqX1vT3aqjQFxn3BXtWwxkZcqTHv6u37lB6qIMXBzguPU/p/KTeQWjWs5K9Xwq895c4Me3MkO/6JXFmVppLrAViYZAOVG010ah9/zXGSC0QuXpqzYF9NyD8um0p1JJJ5xMUEkP/OBpwylCIV9LuMx/7UG+Ed4Hc5hrR5Ln78JUAoCUdR8BD8mDhpGjzDEdP0iOHwnoB2pvVXHk1vwmBcxMdV+doFTY1on9DDNs+zyKhWpHP43mizwi/2KdVlgxo77hrIZv2Zfsm6L13t2hpAs3TbVCQKCQkeTK3W6NBwGd/14PIZ5lTX4OrtEgLOL+DRHFkoO3JnuzAsBAAZuO/WayjdXfJs+NnKoeNEQtAmnUMgb3EBZ7UCDSOls8OKK/kvYT2bj0R8oMoE5C46O4gPbve2XU9E5URQ4d2L5ZFlRk3KN/bnbMnst3/J5VkmwH+qMDnGEth34ayGvOr3q2Y/gPBZVE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
